general:
  seed: 42
  run_id: 'btwt-b-b32-e5-soft'

data:
  use_full_dataset: True
  max_samples: null
  eval_split: 0.05
  path: '../twitter-datasets/'
  checkpoint_path: 'checkpoints/'
  dedup_strategy: 'smooth'
  smoothing_epsilon: 0.01

llm:
  model: 'vinai/bertweet-base'
  resume_from_checkpoint: null
  use_fp16: False
  use_lora: False
  lora_r: 16
  lora_alpha: 32
  max_len: 64
  epochs: 3
  lr: 1.e-4
  warmup_steps: 500
  batch_size: 32
  gradient_accumulation_steps: 1
  weight_decay: 0.01

lstm:
  resume_from_checkpoint: null
  bidirectional: True
  batch_size: 128
  epochs: 40
  embedding_dim: 10 
  hidden_dim: 100
  layers: 2
