general:
  seed: 42
  run_id: 'ensemble-6'

data:
  use_full_dataset: True
  max_samples: null
  eval_split: 0.05
  path: '../twitter-datasets/'
  checkpoint_path: 'checkpoints/'
  dedup_strategy: 'smooth'
  smoothing_epsilon: 0.01

llm:
  model: 'vinai/bertweet-large'
  resume_from_checkpoint: null
  use_fp16: False
  use_lora: False
  lora_r: 16
  lora_alpha: 32
  max_len: 64
  epochs: 3
  lr: 2.e-5
  warmup_steps: 500
  batch_size: 32
  gradient_accumulation_steps: 1
  weight_decay: 0.01

ensemble:
  path: 'ensemble/'
  models: [
    'btwt-b-b32-e5-smooth',
    'btwt-b-b64-e5-smooth',
    'btwt-b-b32-e5-soft',
    'btwt-b-b32-e5-none',
    'rbrt-b-b32-e5-smooth',
    'rbrt-b-b32-e5-hard',
  ]
  base_models: [
    'vinai/bertweet-base',
    'vinai/bertweet-base',
    'vinai/bertweet-base',
    'vinai/bertweet-base',
    'cardiffnlp/twitter-roberta-base-sentiment-latest',
    'cardiffnlp/twitter-roberta-base-sentiment-latest'
  ]