general:
  seed: 42
  run_id: 'bertweet-large-d200'

data:
  use_full_dataset: False
  max_samples: null
  path: '../twitter-datasets/'
  checkpoint_path: 'checkpoints/'
  soft_labels: True

llm:
  model: 'vinai/bertweet-large'
  # model: 'checkpoints/<checkpoint-folder>'
  special_tokens: False
  use_lora: False
  lora_r: 16
  lora_alpha: 32
  max_len: 128
  epochs: 3
  lr: 2.e-5
  warmup_steps: 500
  batch_size: 16
  gradient_accumulation_steps: 1
  weight_decay: 0.01
