general:
  seed: 42
  run_id: 'btwt-b-fp32-b32-d200'

data:
  use_full_dataset: True
  max_samples: null
  path: '../twitter-datasets/'
  checkpoint_path: 'checkpoints/'
  soft_labels: True

llm:
  model: 'vinai/bertweet-base'
  resume_from_checkpoint: 'checkpoints/btwt-b-fp32-b32-s2000/checkpoint-171744'
  use_fp16: False
  use_lora: False
  lora_r: 16
  lora_alpha: 32
  max_len: 128
  epochs: 5
  lr: 2.e-5
  warmup_steps: 500
  batch_size: 32
  gradient_accumulation_steps: 1
  weight_decay: 0.01
