general:
  seed: 42
  run_id: 'logit'

data:
  use_full_dataset: False
  max_samples: null
  eval_split: 0.05
  path: '../twitter-datasets/'
  checkpoint_path: 'checkpoints/'
  dedup_strategy: 'hard'
  smoothing_epsilon: 0.01

llm:
  model: 'vinai/bertweet-base'
  resume_from_checkpoint: null
  use_fp16: False
  use_lora: False
  lora_r: 16
  lora_alpha: 32
  max_len: 128
  epochs: 3
  lr: 1.e-4
  warmup_steps: 500
  batch_size: 32
  gradient_accumulation_steps: 1
  weight_decay: 0.01

logit: 
  max_iter: 1000
  max_features: 1000

rf:
  n_estimators: 100
  max_features: 1000
  max_depth: 100
