general:
  seed: 42

data:
  use_full_dataset: False
  path: '../twitter-datasets/'

hf:
  model: 'vinai/bertweet-large'
  train_batch: 128
  test_batch: 128
  max_len: 64

model:
  embedding_dim: 10 
  hidden_dim: 100
  layers: 2
  epochs: 40
  out_path: './checkpoints/no_duplicates'
  checkpoint_path: False